name: Lab 1

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Get the latest changes

      - uses: actions/setup-python@v5
        name: Setup Python
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install nbconvert
